{"name": "test_add2[【类型】输入为空，给出提示信息2]", "status": "passed", "steps": [{"name": "步骤一：-3和开始计算，预期应等于参数大小超出范围，打印<ExceptionInfo for raises contextmanager>", "status": "broken", "statusDetails": {"message": "TypeError: '>' not supported between instances of 'str' and 'int'\n", "trace": "  File \"D:\\zj\\PycharmProjects\\study202208\\study0818\\test\\test_calculate.py\", line 53, in test_add2\n    result=self.cal.add(x,y)\n  File \"D:\\zj\\PycharmProjects\\study202208\\script\\calculator.py\", line 4, in add\n    if a > 99 or a < -99 or b > 99 or b < -99:\n"}, "start": 1660806013576, "stop": 1660806013576}], "attachments": [{"name": "log", "source": "854b13d1-1c71-43a9-a185-80555afde4ff-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "6a4860e8-2821-406c-9ce5-5b7364e9793f-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "f94b044c-766c-4674-bce6-c9dc4133f27b-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "x", "value": "-3"}, {"name": "y", "value": "''"}, {"name": "expect", "value": "'参数大小超出范围'"}], "start": 1660806013576, "stop": 1660806013576, "uuid": "5956a48b-ab9a-4de2-b9bd-6050f5525d19", "historyId": "0412f9eaf97e435531107a7fcdc7ef69", "testCaseId": "c1fd4152c4894ab47d6f7448dc1c5bcf", "fullName": "study0818.test.test_calculate.TestAdd#test_add2", "labels": [{"name": "feature", "value": "加法计算模块"}, {"name": "story", "value": "加法报错用例"}, {"name": "tag", "value": "P2"}, {"name": "parentSuite", "value": "study0818.test"}, {"name": "suite", "value": "test_calculate"}, {"name": "subSuite", "value": "TestAdd"}, {"name": "host", "value": "LAPTOP-BEO6NH7O"}, {"name": "thread", "value": "21868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "study0818.test.test_calculate"}]}