{
  "uid" : "ce0d2e0e56a4de98",
  "name" : "test_add1[None-9.3-参数大小超出范围]",
  "fullName" : "test.cases.add.test_add.TestAdd#test_add1",
  "historyId" : "f1fb12f221274d81bd8eddb44558d600",
  "time" : {
    "start" : 1660620753137,
    "stop" : 1660620753137,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "TypeError: '>' not supported between instances of 'NoneType' and 'int'",
  "statusTrace" : "self = <test.cases.add.test_add.TestAdd object at 0x000002A6A2915A20>, x = None, y = 9.3\nz = '参数大小超出范围'\n\n    @pytest.mark.add\n    @pytest.mark.parametrize('x,y,z',yaml.safe_load(open(my_dir+\"/adddata.yaml\")))\n    def test_add1(self,x,y,z):\n        # with allure.step():\n        self.cal=Calculator()\n>       result=self.cal.add(x,y)\n\ntest\\cases\\add\\test_add.py:18: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <script.calculator.Calculator object at 0x000002A6A2983F60>, a = None, b = 9.3\n\n    def add(self, a, b):\n    \n>       if a > 99 or a < -99 or b > 99 or b < -99:\nE       TypeError: '>' not supported between instances of 'NoneType' and 'int'\n\nscript\\calculator.py:4: TypeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_xunit_setup_method_fixture_TestAdd",
    "time" : {
      "start" : 1660620753136,
      "stop" : 1660620753136,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "hasContent" : false,
    "stepsCount" : 0
  }, {
    "name" : "_xunit_setup_class_fixture_TestAdd",
    "time" : {
      "start" : 1660620753061,
      "stop" : 1660620753062,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "hasContent" : false,
    "stepsCount" : 0
  } ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "TypeError: '>' not supported between instances of 'NoneType' and 'int'",
    "statusTrace" : "self = <test.cases.add.test_add.TestAdd object at 0x000002A6A2915A20>, x = None, y = 9.3\nz = '参数大小超出范围'\n\n    @pytest.mark.add\n    @pytest.mark.parametrize('x,y,z',yaml.safe_load(open(my_dir+\"/adddata.yaml\")))\n    def test_add1(self,x,y,z):\n        # with allure.step():\n        self.cal=Calculator()\n>       result=self.cal.add(x,y)\n\ntest\\cases\\add\\test_add.py:18: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <script.calculator.Calculator object at 0x000002A6A2983F60>, a = None, b = 9.3\n\n    def add(self, a, b):\n    \n>       if a > 99 or a < -99 or b > 99 or b < -99:\nE       TypeError: '>' not supported between instances of 'NoneType' and 'int'\n\nscript\\calculator.py:4: TypeError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "7bdfdac593c6bf0a",
      "name" : "stdout",
      "source" : "7bdfdac593c6bf0a.txt",
      "type" : "text/plain",
      "size" : 26
    } ],
    "parameters" : [ ],
    "shouldDisplayMessage" : true,
    "attachmentsCount" : 1,
    "hasContent" : true,
    "stepsCount" : 0
  },
  "afterStages" : [ {
    "name" : "_xunit_setup_method_fixture_TestAdd::0",
    "time" : {
      "start" : 1660620753142,
      "stop" : 1660620753142,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "hasContent" : false,
    "stepsCount" : 0
  }, {
    "name" : "_xunit_setup_class_fixture_TestAdd::0",
    "time" : {
      "start" : 1660620753161,
      "stop" : 1660620753161,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "hasContent" : false,
    "stepsCount" : 0
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "add"
  }, {
    "name" : "parentSuite",
    "value" : "test.cases.add"
  }, {
    "name" : "suite",
    "value" : "test_add"
  }, {
    "name" : "subSuite",
    "value" : "TestAdd"
  }, {
    "name" : "host",
    "value" : "LAPTOP-BEO6NH7O"
  }, {
    "name" : "thread",
    "value" : "11036-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test.cases.add.test_add"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "x",
    "value" : "None"
  }, {
    "name" : "y",
    "value" : "9.3"
  }, {
    "name" : "z",
    "value" : "'参数大小超出范围'"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "add" ]
  },
  "source" : "ce0d2e0e56a4de98.json",
  "parameterValues" : [ "None", "9.3", "'参数大小超出范围'" ]
}